# Generated by Django 6.0 on 2026-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=200)),
                ('purchasedItem', models.CharField(max_length=200)),
                ('manufactureDate', models.DateField()),
                ('expiryDate', models.DateField()),
            ],
        ),
    ]
