# Generated by Django 6.0 on 2026-01-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('playerArm', models.CharField(max_length=100)),
                ('instaFollowers', models.IntegerField()),
            ],
        ),
    ]
