# Generated by Django 6.0 on 2026-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ModelName', models.CharField(max_length=200)),
                ('ProductPrize', models.IntegerField()),
                ('Processor', models.CharField(max_length=100)),
                ('DeliveryDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
