# Generated by Django 6.0 on 2026-01-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerName', models.CharField(max_length=100)),
                ('classType', models.CharField(max_length=100)),
                ('IdProof', models.IntegerField()),
                ('startStation', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
