# Generated by Django 6.0 on 2026-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='IdProof',
            field=models.CharField(max_length=100),
        ),
    ]
