# Generated by Django 6.0 on 2026-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=100)),
                ('whichCountry', models.CharField(max_length=100)),
                ('PlayedMatches', models.IntegerField()),
                ('centuries', models.IntegerField()),
            ],
        ),
    ]
