# Generated by Django 6.0 on 2026-01-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('authorName', models.CharField(max_length=100)),
                ('pickupDate', models.DateField()),
                ('receivedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('on hold', 'On Hold')])),
            ],
        ),
    ]
