# Generated by Django 6.0 on 2026-01-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('on hold', 'On Hold')], max_length=100),
        ),
    ]
